name: Generate docs

on:
  release:
    types: [released]

jobs:
  gen:
    name: Generate and deploy docs
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v3
      - name: Cache nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.0.0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate
        run: |
          nimble install -d -y
          nimble docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
